name: Brinkley Tests
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Download Godot
        run: |
          curl -L -o godot.zip https://github.com/godotengine/godot/releases/download/4.5.1-stable/Godot_v4.5.1-stable_mono_win64.zip
          Expand-Archive -Path godot.zip -DestinationPath .
      - name: Import project
        run: ./Godot_v4.5.1-stable_mono_win64/Godot_v4.5.1-stable_mono_win64.exe --path . --headless --import
      - name: Run tests
        run: ./Godot_v4.5.1-stable_mono_win64/Godot_v4.5.1-stable_mono_win64.exe --path . --headless --script Scripts/Testing/gametest.gd
